### ISSUE TITLE
Finder Selection Tests

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#101]
Check that enableFinders are the same as that we are expecting.
- [ ] Go to the "Code" page directly and with no reload
- [ ] Go to a .puml file view page directly and with no reload
- [ ] Go to .puml raw file page directly (and with no reload?)
- [ ] Go to a non-PlantUML file view page directly and with no reload
- [ ] Go to non-PlantUML raw file page directly (and with no reload?)
- [ ] Go to one of issues page directly and with no reload
- [ ] Go to one of pull requests page directly and with no reload
- [ ] Go to commits page of a pull request and with no reload
- [ ] Go to files page of a pull request and with no reload
- [ ] Go to another GitHub page directly and with no reload
- [ ] Go to non-GitHub page directly

**Comment by exKAZUu** [comment]
I decide to cancel this issue because this extension requires e2e tests and it is too costly to write such e2e tests
