### ISSUE TITLE
Code Block Test

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#102]
Check that GitHubCodeBlockFinders can find code blocks on GitHub pages appropriately
- [ ] Go to https://github.com/WillBooster/plantuml-visualizer
- [ ] Go to https://github.com/WillBooster/plantuml-visualizer/issues/54
- [ ] Go to https://github.com/WillBooster/plantuml-visualizer/issues/102

**Comment by exKAZUu** [comment]
I decide to cancel this issue because this extension requires e2e tests and it is too costly to write such e2e tests
