### ISSUE TITLE
feat: beautify design of before/after images (mainly labels)

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/plantuml-visualizer#114]
今は特に装飾などをせずに before / after のブランチ名を表示しているが、もうちょいかっちょよくしてみたい。

**Comment by rdrgn** [comment]
@exKAZUu この拡張の機能の全容を把握していないため「before / after のブランチ名」とは何のことかお教え願います。

**Comment by exKAZUu** [comment]
@rdrgn すまん、拡張を入れた状態で https://github.com/WillBooster/plantuml-visualizer/pull/24/files を開いてみてもらえんかな。
あとでスクショもはるわ。

**Comment by exKAZUu** [comment]
![image](https://user-images.githubusercontent.com/436237/60928231-96a43600-a2e7-11e9-8355-ed8a4a6860a8.png)

**Comment by exKAZUu** [comment]
https://github.com/WillBooster/plantuml-visualizer/blob/master/src/Mutator.ts#L43
ここらへんかな
