### ISSUE TITLE
Allow user to disable this plugin in popup window

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/plantuml-visualizer#14]
現状のポップアップウィンドウには、 `Render App` ボタンのみが表示されている。
上記ボタンを削除して、その代りに、プラグインを一時的に無効化するためのUIおよび機能を実装する。

**Comment by kumachan-mis** [comment]
アサインありがとうございます.
#25 よりこちらの方が優先だと思うので, こちらから取り組みます

無効化ボタン(まだボタンと決まったわけでは無いですが)が押されたら, activeFinderを空のリストに保っておくようにすることで実現しようと思っています.

これを参考に作ってみます.
http://rugger-sr.github.io/blog/2015/10/23/chrome_extension_toggle_button/
