### ISSUE TITLE
fix: visualize PlantUML description when submitting/updating an issue or showing its preview

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/plantuml-visualizer#153]
The extension doesn't visualize the following PlantUML description (just as an example) in `Preview` tab and doesn't visualize it after submitting/updating this content.

```puml
@startuml
[*] --> State
@enduml
```

**Comment by kumachan-mis** [comment]
The mutation observer doesn't seem to work in these situations.
We might have to refine mutation observer's option...?
https://developer.mozilla.org/ja/docs/Web/API/MutationObserver#MutationObserverInit
