### ISSUE TITLE
Show message near code blocks or a viewed file to notice the usage

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#20]
Without messages, users cannot know the usage of this extension or whether it is available.
The extension must show a message like "Click Here!!" near code blocks, a viewed file or UML images.

After #12

**Comment by exKAZUu** [comment]
最初から画像を挿入しているので、なくても良いかも？（そんなに強い意見ではない）

**Comment by kumachan-mis** [comment]
初期状態がテキストだと思っていた時に立てたので, 不要な場合はクローズしていただいて大丈夫です.

**Comment by exKAZUu** [comment]
なくても大丈夫だと思ったので閉じます！
