### ISSUE TITLE
Show before/after PlantUML images in PR's diff

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/plantuml-visualizer#25]
PRのDiff (e.g. https://github.com/WillBooster/plantuml-visualizer/pull/24/files) で修正前と修正後のPlantUML画像を表示する。

以下のコードで、特定のコミット ([7e47f29ea86bdde95fc85f2ee2127bc86df2f81b](https://github.com/WillBooster/plantuml-visualizer/blob/7e47f29ea86bdde95fc85f2ee2127bc86df2f81b/puml-sample/class.pu)) のclass.puのGitHubページを取得できる。修正前コミットと修正後コミットのハッシュさえわかれば、以下のコードを活用してPlantUMLの内容を取り出し、表示させることができるような気がする。

```
fetch('https://github.com/WillBooster/plantuml-visualizer/blob/7e47f29ea86bdde95fc85f2ee2127bc86df2f81b/puml-sample/class.pu')
  .then(function(response) {
    return response.text();
  })
  .then(function(text) {
    console.log(text);
  });
```

**Comment by kumachan-mis** [comment]
入力 : 
・ブランチのトップページのURL(例: https://github.com/WillBooster/plantuml-visualizer/tree/test)
・探索対象のファイルのパス(例: puml-sample/class.pu)
出力 : 
・該当ブランチの先頭コミットにおける該当ファイルのURL(例: https://github.com/WillBooster/plantuml-visualizer/blob/7e47f29ea86bdde95fc85f2ee2127bc86df2f81b/puml-sample/class.pu)

の関数を作るところから始めればいいでしょうかね

**Comment by exKAZUu** [comment]
念のため、PRページからどんな情報が抽出できるか調べてみてもらえない？
もしかしたら、コミットハッシュぐらいは取れないのだろうかと期待。
もし、何も取れなかったら、君の提案通りの関数を作ってもらうのが良さそう！

**Comment by kumachan-mis** [comment]
「検証」でいろいろみてみたんですが, 変更後(test)のコミットハッシュは簡単に取れるんですけど, 変更前(master)のコミットハッシュが取れそうに無いんですよね...

**Comment by exKAZUu** [comment]
おお、既に分析済みか、ありがとう！
となれば、君の提案通りに進めるのがベストだね。お願いします 🙇
