### ISSUE TITLE
The 'Hello World' alert does NOT work

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#26]
When the 'hello' button in the popup window is clicked, a window alert with 'Hello World', is expected to appear, I guess. However, Nothing happens after  the the button is clicked.

Do you know how to solve?

**Comment by kumachan-mis** [comment]
@exKAZUu 
これがわからないと #14 に手がつけられそうにないので, 何かご存知であればご教授ください...!!

**Comment by exKAZUu** [comment]
それって、普通のWebサイトで動かしてみた？Chrome起動時のホームページみたいな、通常のWebページ以外ではalertが動かないはず。

**Comment by kumachan-mis** [comment]
もしかして, manifest.json内で, content_scripts > matchesが"https://github.com/*"になっているから, GitHubのウェブページじゃないと動かないのは正解ですか？
今このページで動かしたら動いたのですが, twitterとかgoogleの普通の検索結果ページだと動かなくなるようです.

**Comment by exKAZUu** [comment]
あー、それだー！

**Comment by kumachan-mis** [comment]
了解です！クローズします.
今はGitHub以外での利用を想定していないので, この部分は変更しないでおきますね.

**Comment by exKAZUu** [comment]
そうね！将来的には複数のサイトに対応するかもしれない。(そのためには結構コードの設計を変えないといけないんだよなー)
