### ISSUE TITLE
Cannot build project, start project, etc

### ISSUE THREAD

**Issue by AleksandrSokolov** [WillBooster/plantuml-visualizer#436]
saa@LAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

saa@LAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$ yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'

yarnLAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

saa@LAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$
saa@LAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$ yarn package
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'package'

saa@LAPTOP-ASOKOLOV:~/gplantuml/plantuml-visualizer$ yarn start
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

**Comment by kumachan-mis** [comment]
The errors don't seem to come from our product, but from yarn in Ubuntu.
Please check the following pages:
https://github.com/yarnpkg/yarn/issues/2821, https://github.com/yarnpkg/yarn/issues/3708
