### ISSUE TITLE
Cannot work with local files file:/

### ISSUE THREAD

**Issue by AleksandrSokolov** [WillBooster/plantuml-visualizer#437]

**Comment by kumachan-mis** [comment]
Is this a duplicate of #436 ?
If not, please give us more information

**Comment by exKAZUu** [comment]
Okay, I confirm the extension in the Chrome Web Store cannot visualize PlantUML files of `file://` .

**Comment by kumachan-mis** [comment]
Don't you forget to allow our product to access to your local files?

If you use Chrome, please try:
1. go to chrome://extensions/?id=ffaloebcmkogfdkemcekamlmfkkmgkcf
2. click “Allow access to file URLs”
3. reload your local file with your browser

If you use Firefox, you may not need any extra settings
related issue: https://github.com/facebook/react-devtools/issues/1324
