### ISSUE TITLE
Firefox plugin seems to fail for a private repository

### ISSUE THREAD

**Issue by arkban** [WillBooster/plantuml-visualizer#443]
We have a PlantUML diagram on a private repository, and the PlantUML viewer doesn't display anything. It hides the source block but doesn't display anything in it's place.

**Comment by exKAZUu** [comment]
@arkban I can visualize https://github.com/XXX/YYY/blob/master/docs/architecture.pu (Note: XXX/YYY is a private repo in GitHub) with our Chrome extension.
Could you explain what resource type of PlantUML diagram cannot be visualized?
 (e.g. `https://github.com/XXX/YYY/blob/master/docs/architecture.pu`, code blocks in `https://github.com/XXX/YYY/blob/master/README.md` or `https://github.com/XXX/YYY/pull/ZZZ`)

**Comment by exKAZUu** [comment]
@arkban Sorry for the inconvenience. We've fixed some bugs in the Firefox extension, so I'll close this. If you still face any issue, please reopen and share the above information (e.g. urls).
