### ISSUE TITLE
Feature request: support GitLab

### ISSUE THREAD

**Issue by TeNNoX** [WillBooster/plantuml-visualizer#484]
Would be awesome.

1. Wiki
2. Editing files

**Comment by kumachan-mis** [comment]
@emtsubasa 
After #546
General <pre> tag finder will support GitLab partly

**Comment by exKAZUu** [comment]
@TeNNoX We've released `v1.10.0` (chrome version requires some time for review ...) which supports any <pre> tag with `@startuml` prefix and `@enduml` suffix.
I hope this change makes the extension supports wide web sites including GitLab. So could you re-test it?
If you find some pages where `v1.10.0` or higher still doesn't work well, please inform me such urls :bow:

**Comment by TeNNoX** [comment]
So on gitlab wiki it works now :)

But it seems a bit greedy now, as you can see here :sweat_smile: 

Before:
![Screenshot from 2021-03-31 18-00-17](https://user-images.githubusercontent.com/2084639/113174884-1f48cf80-924b-11eb-8da8-5b577881cf18.png)
After:
![Screenshot from 2021-03-31 18-00-40](https://user-images.githubusercontent.com/2084639/113174890-2243c000-924b-11eb-882b-6c1515298025.png)

**Comment by kumachan-mis** [comment]
@TeNNoX Thanks for error reporting.
#566 will fix the bug. So please try again.

**Comment by exKAZUu** [comment]
`v1.10.1` should fix the new bug. Thanks!
