### ISSUE TITLE
Update PlantUML version on willbooster-plantuml.herokuapp.com

### ISSUE THREAD

**Issue by Potherca** [WillBooster/plantuml-visualizer#547]
As can be seen at https://willbooster-plantuml.herokuapp.com/version or by using the plugin on this code:

```
@startuml
version
@enduml
```

the current PlantUML version used is `1.2020.15`, from June 2020. (261 days at the time of this writing). 

Since then many changes and features have been added to PlantUML that we are now missing out on.

This also makes diagram break that use such new features.

Could the PlantUML server be updated, please?

On a side note... if #502 were implemented, issues such as this would become less urgent, as one could simply switch to a more up-to-date server.

**Comment by exKAZUu** [comment]
@Potherca We've updated the server. But as you pointed out, I understand we should allow users to select a visualizer server. We plan to support the feature soon.

**Comment by kumachan-mis** [comment]
> We plan to support the feature soon

The configuration popup is now experimentally implemented! (v1.8.0)

**Comment by Potherca** [comment]
I just saw the new popup.

![Screenshot at 2021-03-24 11-03-53](https://user-images.githubusercontent.com/195757/112292265-360e8580-8c91-11eb-9f7a-a82b2c27826b.png)

Awesome work! I love it! :heart_eyes:
