### ISSUE TITLE
chore: fix the lint config for SCSS on Svelte

### ISSUE THREAD

**Issue by rdrgn** [WillBooster/plantuml-visualizer#576]
`yarn lint` fails to parse SCSS.

Example
https://github.com/WillBooster/plantuml-visualizer/runs/2258228841

**Comment by rdrgn** [comment]
to merge #573

**Comment by rdrgn** [comment]
It seems that all we can do is just disable the lint for SCSS... Realy?

```diff
   settings: {
+    'svelte3/ignore-styles': (attributes) => attributes.lang === 'scss',
     'svelte3/typescript': require('typescript'),
   },
```

**Comment by kumachan-mis** [comment]
I found the ignorance you show too
