### ISSUE TITLE
Cannot visualize the whole of a large diagram

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#85]
see https://github.com/WillBooster/plantuml-visualizer/pull/84/files

**Comment by exKAZUu** [comment]
Hm, I think this is due to a limitation of PlantUML server.
Can you visualize the above content with another PlantUML viewer? (e.g. VSCode plugin)

**Comment by kumachan-mis** [comment]
@exKAZUu 
Of course, Yes.
This issue does not come from PlantUML itself, but from our visualizer

**Comment by kumachan-mis** [comment]
This may be solved by adding style 
`overflow: auto`
to plantUML images' area

**Comment by exKAZUu** [comment]
Great :+1:

**Comment by kumachan-mis** [comment]
`overflow: auto` has no mean...
A image itself seems to be limited.
I wonder what VSCode plugin do.

**Comment by kumachan-mis** [comment]
"サイズの大きな図を作成したい" of http://plantuml.com/ja/faq gives us a hint...?

**Comment by exKAZUu** [comment]
Yeah, I mean, it is due to a limitation of the **official server** (not PlantUML tool itself).
To overcome the limitation, we should host our server, but it takes some costs, so I'm not willing to that currently.

**Comment by kumachan-mis** [comment]
I see...
