### ISSUE TITLE
How to set plantuml.com/plantuml as server?

### ISSUE THREAD

**Issue by VladimirAlexiev** [WillBooster/plantuml-visualizer#861]
Hi! thanks for this very useful addon!

Instead of your default server https://plantuml-service-willbooster.fly.dev
![image](https://user-images.githubusercontent.com/536250/235308068-08f36ebd-fe52-4c19-8f91-aa3a6fc3efe3.png)

I want to use https://www.plantuml.com/plantuml/, which is always at the latest version:
![image](https://user-images.githubusercontent.com/536250/235308032-c924b894-43ef-4432-bb0b-1c952e5996a2.png)

The reason is that I'm always testing new/changing features, so I need the latest server

I've read the README and https://github.com/WillBooster/plantuml-visualizer/issues/604 and I think https://www.plantuml.com/plantuml/ is a valid server URL (uses HTTPS not HTTP). But when I set it, I get this error:
![image](https://user-images.githubusercontent.com/536250/235308161-0ceff4b3-1aeb-4aa4-892a-11c67c5730c3.png)

I think the reason is that your serve https://github.com/WillBooster/plantuml-service
(cloned from https://github.com/bitjourney/plantuml-service)
uses a different invocation than the original server:
https://github.com/bitjourney/plantuml-service#get-svgsource says "percent encoded" 
but the original uses https://plantuml.com/text-encoding

**Comment by exKAZUu** [comment]
Thanks, we understand your use case. We will fix the plugin to work on the official server, too.

**Comment by VladimirAlexiev** [comment]
@exKAZUu and @kumachan-mis thanks a lot for the fix!
Now it works with https://www.plantuml.com/plantuml/.
(I'm testing with code in https://github.com/plantuml/plantuml/issues/72).
