### ISSUE TITLE
bug: a cloned image appears

### ISSUE THREAD

**Issue by kumachan-mis** [WillBooster/plantuml-visualizer#87]
Can you guess what happens?
![](https://user-images.githubusercontent.com/29433058/60269261-12d26d00-9929-11e9-8247-22afe2bd2952.png)

If I reload the page, the visualizer seems to work well.
MutationObserver may do something bad.

**Comment by kumachan-mis** [comment]
Sorry. `master` has no problem. I close this.

**Comment by exKAZUu** [comment]
hm, i think https://github.com/WillBooster/plantuml-visualizer/blob/master/src/Mutator.ts#L13 is related to this bug.

**Comment by exKAZUu** [comment]
I suspect that `nextImgElement.src.startsWith(ImageSrcPrefix)` is now always `false`. Could you debug this part?
