### ISSUE TITLE
The extension's server is down

### ISSUE THREAD

**Issue by tocic** [WillBooster/plantuml-visualizer#893]
The extension has stopped working for me. It seems like the problem is that the server https://plantuml-service-willbooster.fly.dev is [down](https://www.isitdownrightnow.com/plantuml-service-willbooster.fly.dev.html). The extension's window prints the following message:

> https://plantuml-service-willbooster.fly.dev does not refer a valid plantUML serer

**Comment by tocic** [comment]
@exKAZUu could you please look at this?

**Comment by exKAZUu** [comment]
@tocic Sorry for the inconvenience. I've fixed the server issue.
